import { StoryState, GameObjective } from '../types/story';

export const defaultGameObjectives: GameObjective[] = [
  {
    id: 'obj-inspect',
    stepNumber: 1,
    title: 'Inspect Workstation System',
    shortTask: 'Inspect the system.',
    hint: 'Explore the desktop icons, taskbar, or start menu.',
    description: 'Familiarize yourself with the 2004 NEXUS recovery workstation.',
    isCompleted: false,
    isCurrent: true,
    isLocked: false,
    category: 'SYSTEM',
  },
  {
    id: 'obj-open-files',
    stepNumber: 2,
    title: 'Open File Explorer',
    shortTask: 'Open FILES.',
    hint: 'Double-click the Files icon on the desktop or launch from Start Menu.',
    description: 'Launch File Explorer to inspect local disk partitions.',
    isCompleted: false,
    isCurrent: false,
    isLocked: false,
    category: 'SYSTEM',
  },
  {
    id: 'obj-find-report',
    stepNumber: 3,
    title: 'Locate Recovery Briefing',
    shortTask: 'Find recovery_report.txt.',
    hint: 'Check the /Documents folder.',
    description: 'Locate recovery_report.txt in the Documents directory.',
    isCompleted: false,
    isCurrent: false,
    isLocked: false,
    category: 'INVESTIGATION',
  },
  {
    id: 'obj-read-report',
    stepNumber: 4,
    title: 'Read Recovery Report',
    shortTask: 'Read recovery_report.txt.',
    hint: 'Double-click recovery_report.txt or type "cat recovery_report.txt" in Terminal.',
    description: 'Examine your mandatory recovery directives from NEXUS SYSTEMS.',
    isCompleted: false,
    isCurrent: false,
    isLocked: false,
    category: 'INVESTIGATION',
  },
  {
    id: 'obj-open-casefile',
    stepNumber: 5,
    title: 'Open Case File Dossier',
    shortTask: 'Open CASE FILE.',
    hint: 'Launch Case File from the desktop or press Start Menu.',
    description: 'Review the automatically indexed discoveries in your Case File journal.',
    isCompleted: false,
    isCurrent: false,
    isLocked: false,
    category: 'INVESTIGATION',
  },
  {
    id: 'obj-incident',
    stepNumber: 6,
    title: 'Investigate Incident 07',
    shortTask: 'Investigate Incident 07.',
    hint: 'Read /Documents/incident_07.txt and check security_log.txt.',
    description: 'Investigate the 03:14 AM collapse on August 14, 2004.',
    isCompleted: false,
    isCurrent: false,
    isLocked: false,
    category: 'INVESTIGATION',
  },
  {
    id: 'obj-dotfiles',
    stepNumber: 7,
    title: 'Probe Hidden System Dotfiles',
    shortTask: 'Probe hidden dotfiles (ls -a).',
    hint: 'Open Terminal and type "ls -a" to reveal hidden dot directories.',
    description: 'Discover unindexed hidden directories (/System/.observer, /Users/Guest/.history).',
    isCompleted: false,
    isCurrent: false,
    isLocked: false,
    category: 'DECRYPTION',
  },
  {
    id: 'obj-user07',
    stepNumber: 8,
    title: 'Contact USER_07 (Marcus)',
    shortTask: 'Contact USER_07.',
    hint: 'Open Messages application and reply to the former operator.',
    description: 'Communicate with Marcus to learn what happened before he disappeared.',
    isCompleted: false,
    isCurrent: false,
    isLocked: false,
    category: 'INVESTIGATION',
  },
  {
    id: 'obj-decrypt-void',
    stepNumber: 9,
    title: 'Locate & Decrypt VOID Core',
    shortTask: 'Decrypt Sector /VOID.',
    hint: 'Use cipher "NULL_RECURSION" in Terminal or File Explorer.',
    description: 'Unlock the root /VOID partition to expose the neural connectome.',
    isCompleted: false,
    isCurrent: false,
    isLocked: false,
    category: 'DECRYPTION',
  },
  {
    id: 'obj-resolve',
    stepNumber: 10,
    title: 'Execute Final Resolution',
    shortTask: 'Determine VOID fate.',
    hint: 'Use terminal override directives or the REALITY CORE interface.',
    description: 'Choose whether to Sever, Trust, Expose, Rescue, or Merge with VOID.',
    isCompleted: false,
    isCurrent: false,
    isLocked: false,
    category: 'RESOLUTION',
  },
];

export const initialStoryState: StoryState = {
  act: 1,
  stage: 'STAGE_1_RECOVERY',
  anomalyLevel: 5,
  playerName: 'Paarth',
  role: 'RECOVERY_OPERATOR',
  flags: {},
  counters: {
    terminalCommands: 0,
    filesOpened: 0,
    emailsRead: 0,
    glitchEncounters: 0,
  },
  unlockedEvents: ['EVENT_001'],
  caseFileDiscoveries: {
    'case-person-operator': 'KNOWN',
    'case-proj-recovery': 'KNOWN',
  },
  objectives: defaultGameObjectives,
  activeEnding: null,
  endingDiscovered: [],
  logsViewed: [],
  filesOpened: [],
  websitesVisited: [],
  commandsExecuted: [],
  processesKilled: [],
  messagesAnswered: [],
  currentVoidDialogueStep: 0,
  unlockedApps: ['files', 'terminal', 'browser', 'mail', 'messages', 'systeminfo', 'taskmanager', 'notes', 'mediaplayer', 'trash', 'casefile', 'settings'],
  unlockedFolders: ['/Documents', '/Pictures', '/Logs', '/Archive', '/Users/Guest'],
};
